// ...existing code...
export default defineConfig({
  // ...existing code...
  build: {
    // ...existing code...
    rollupOptions: {
      // ...existing code...
      external: [
        // Add your external dependencies here
        "dependency-to-exclude",
      ],
      // ...existing code...
    },
  },
  // ...existing code...
});
